import {FormEvent,useEffect,useMemo,useState} from 'react';import {CalendarDays,CheckCircle2,ChevronDown,Home,LogOut,Menu,Plus,ReceiptText,ShoppingCart,Users,WalletCards} from 'lucide-react';import {supabase} from './lib/supabase';import type {Session} from '@supabase/supabase-js';

type Household={id:string;name:string;invite_code:string};
type ListRow={id:string;title:string};
type EventRow={id:string;title:string;event_date:string;start_time:string|null};
type Tx={id:string;description:string;amount:number;type:string;transaction_date:string};

const money=(n:number)=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ',maximumFractionDigits:0}).format(n);
const today=()=>new Date().toISOString().slice(0,10);
const authRedirectUrl=()=>`${window.location.origin}${import.meta.env.BASE_URL}`;

export default function App(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true);
 const [households,setHouseholds]=useState<Household[]>([]),[household,setHousehold]=useState<Household|null>(null);
 const [tab,setTab]=useState('inicio'),[lists,setLists]=useState<ListRow[]>([]),[events,setEvents]=useState<EventRow[]>([]),[txs,setTxs]=useState<Tx[]>([]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadHouseholds();else{setHouseholds([]);setHousehold(null)}},[session]);
 useEffect(()=>{if(household)loadData(household.id)},[household]);
 async function loadHouseholds(){const {data,error}=await supabase.from('household_members').select('household_id, households(id,name,invite_code)');if(error)return;const rows=(data||[]).map((r:any)=>r.households).filter(Boolean);setHouseholds(rows);if(rows[0])setHousehold(rows[0])}
 async function loadData(id:string){const [{data:l},{data:e},{data:t}]=await Promise.all([supabase.from('lists').select('id,title').eq('household_id',id).order('created_at',{ascending:false}),supabase.from('events').select('id,title,event_date,start_time').eq('household_id',id).gte('event_date',today()).order('event_date').limit(6),supabase.from('transactions').select('id,description,amount,type,transaction_date').eq('household_id',id).order('transaction_date',{ascending:false}).limit(20)]);setLists(l||[]);setEvents(e||[]);setTxs((t||[]) as Tx[])}
 if(loading)return <div className="center"><div className="loader"/></div>;
 if(!session)return <Auth/>;
 if(!household)return <Onboarding onDone={loadHouseholds}/>;
 return <Shell household={household} households={households} tab={tab} setTab={setTab} onSwitch={setHousehold} onRefresh={()=>loadData(household.id)} lists={lists} events={events} txs={txs}/>;
}

function Auth(){
 const [mode,setMode]=useState<'login'|'signup'>('login'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[pendingEmail,setPendingEmail]=useState('');
 useEffect(()=>{const hash=new URLSearchParams(window.location.hash.replace(/^#/,''));
   const error=hash.get('error_description');
   if(error)setMsg(decodeURIComponent(error.replace(/\+/g,' ')));
 },[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const f=new FormData(e.currentTarget),email=String(f.get('email')),password=String(f.get('password')),full_name=String(f.get('name')||'');const res=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name},emailRedirectTo:authRedirectUrl()}});setBusy(false);if(res.error)setMsg(res.error.message);else if(mode==='signup'&&!res.data.session){setPendingEmail(email);setMsg('Revisa tu correo para confirmar la cuenta. El enlace abrirá esta misma aplicación.')}}
 async function resend(){if(!pendingEmail)return;setBusy(true);const {error}=await supabase.auth.resend({type:'signup',email:pendingEmail,options:{emailRedirectTo:authRedirectUrl()}});setBusy(false);setMsg(error?error.message:'Correo de confirmación reenviado. Usa el enlace más reciente.')}
 return <main className="auth"><section className="auth-card"><div className="brand-mark">⌂</div><p className="eyebrow">TU ESPACIO COMPARTIDO</p><h1>Nuestro Hogar</h1><p className="muted">Finanzas, calendario, listas y vida familiar en un solo lugar.</p><form onSubmit={submit}>{mode==='signup'&&<input name="name" placeholder="Nombre completo" required/>}<input name="email" type="email" placeholder="Correo electrónico" required/><input name="password" type="password" minLength={6} placeholder="Contraseña" required/><button disabled={busy}>{busy?'Procesando...':mode==='login'?'Entrar':'Crear cuenta'}</button></form>{msg&&<p className="status">{msg}</p>}{pendingEmail&&<button className="link" disabled={busy} onClick={resend}>Reenviar correo de confirmación</button>}<button className="link" onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'¿Primera vez? Crear cuenta':'Ya tengo cuenta'}</button></section></main>
}

function Onboarding({onDone}:{onDone:()=>void}){
 const [join,setJoin]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {error}=join?await supabase.rpc('join_household',{p_invite_code:String(f.get('value'))}):await supabase.rpc('create_household',{p_name:String(f.get('value'))});setBusy(false);if(error)setMsg(error.message);else onDone()}
 return <main className="auth"><section className="auth-card wide"><p className="eyebrow">BIENVENIDO</p><h1>{join?'Únete a un hogar':'Crea tu hogar'}</h1><p className="muted">{join?'Ingresa el código de invitación que te compartieron.':'Este será el espacio privado para compartir con tu familia.'}</p><form onSubmit={go}><input name="value" placeholder={join?'Código de invitación':'Ej. Nuestro Hogar'} required/><button disabled={busy}>{join?'Unirme':'Crear hogar'}</button></form>{msg&&<p className="status">{msg}</p>}<button className="link" onClick={()=>setJoin(!join)}>{join?'Prefiero crear un hogar':'Ya tengo un código de invitación'}</button></section></main>
}

function Shell(p:any){
 const expense=p.txs.filter((x:Tx)=>x.type==='expense').reduce((a:number,b:Tx)=>a+Number(b.amount),0);
 const income=p.txs.filter((x:Tx)=>x.type==='income').reduce((a:number,b:Tx)=>a+Number(b.amount),0);
 const cards=[['Listas',p.lists.length+' listas','list'],['Calendario',p.events.length?'Próximo: '+p.events[0].title:'Sin eventos próximos','calendar'],['Presupuesto',expense?money(expense)+' gastados':'Registra tu primer gasto','budget'],['Documentos','Próximamente','docs'],['Cumpleaños','Próximamente','birthday'],['Comidas','Próximamente','meal'],['Recetas','Próximamente','recipe'],['Mi familia','Hogar compartido','family']];
 return <div className="app"><header><div><button className="home-select"><span>{p.household.name}</span><ChevronDown size={18}/></button><p>{new Date().toLocaleDateString('es-GT',{weekday:'long',day:'numeric',month:'long'})}</p></div><button className="avatar">S</button></header>
 <main className="content">{p.tab==='inicio'&&<><section className="hero"><div><p className="eyebrow">RESUMEN DEL MES</p><h2>{income?money(Math.max(income-expense,0)):'Todo bajo control'}</h2><p>{income?'Disponible después de tus movimientos':'Empieza agregando tus finanzas, listas y eventos.'}</p></div><div className="hero-icon"><Home/></div></section><div className="section-title"><h3>Tu hogar</h3><button><Menu size={18}/></button></div><section className="grid">{cards.map(([a,b,c])=><button className="module" key={a} onClick={()=>{if(c==='list')p.setTab('listas');if(c==='calendar')p.setTab('calendario');if(c==='budget')p.setTab('presupuesto');if(c==='family')p.setTab('familia')}}><div><strong>{a}</strong><span>{b}</span></div><Icon kind={c}/></button>)}</section></>}
 {p.tab==='listas'&&<Lists household={p.household} lists={p.lists} refresh={p.onRefresh}/>}
 {p.tab==='calendario'&&<Events household={p.household} events={p.events} refresh={p.onRefresh}/>}
 {p.tab==='presupuesto'&&<Budget household={p.household} txs={p.txs} refresh={p.onRefresh}/>}
 {p.tab==='familia'&&<Family household={p.household}/>}
 </main><nav><button className={p.tab==='inicio'?'active':''} onClick={()=>p.setTab('inicio')}><Home/><span>Inicio</span></button><button className={p.tab==='calendario'?'active':''} onClick={()=>p.setTab('calendario')}><CalendarDays/><span>Calendario</span></button><button className="fab" onClick={()=>p.setTab('listas')}><Plus/></button><button className={p.tab==='presupuesto'?'active':''} onClick={()=>p.setTab('presupuesto')}><WalletCards/><span>Finanzas</span></button><button className={p.tab==='familia'?'active':''} onClick={()=>p.setTab('familia')}><Users/><span>Familia</span></button></nav></div>
}

function Icon({kind}:{kind:string}){const map:any={list:<CheckCircle2/>,calendar:<CalendarDays/>,budget:<WalletCards/>,family:<Users/>,docs:<ReceiptText/>,birthday:<CalendarDays/>,meal:<ShoppingCart/>,recipe:<ReceiptText/>};return <span className={'ico '+kind}>{map[kind]}</span>}

function Page({title,subtitle,children}:{title:string;subtitle:string;children:any}){return <section><p className="eyebrow">NUESTRO HOGAR</p><h2 className="page-title">{title}</h2><p className="muted">{subtitle}</p>{children}</section>}

function Lists({household,lists,refresh}:any){const [title,setTitle]=useState('');async function add(e:FormEvent){e.preventDefault();if(!title.trim())return;await supabase.from('lists').insert({household_id:household.id,title:title.trim()});setTitle('');refresh()}return <Page title="Listas" subtitle="Compras, pendientes y todo lo que quieran recordar."><form className="quick" onSubmit={add}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nueva lista"/><button><Plus size={18}/></button></form><div className="stack">{lists.map((l:ListRow)=><article className="row" key={l.id}><span className="rowicon"><CheckCircle2/></span><div><strong>{l.title}</strong><small>Lista compartida</small></div></article>)}{!lists.length&&<Empty text="Aún no hay listas."/ >}</div></Page>}

function Events({household,events,refresh}:any){const [show,setShow]=useState(false);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await supabase.from('events').insert({household_id:household.id,title:String(f.get('title')),event_date:String(f.get('date')),start_time:String(f.get('time')||'')||null});setShow(false);refresh()}return <Page title="Calendario" subtitle="Los próximos momentos importantes de la familia."><button className="primary compact" onClick={()=>setShow(!show)}><Plus size={17}/> Nuevo evento</button>{show&&<form className="panel formgrid" onSubmit={add}><input name="title" placeholder="Evento" required/><input name="date" type="date" defaultValue={today()} required/><input name="time" type="time"/><button>Guardar</button></form>}<div className="stack">{events.map((e:EventRow)=><article className="row" key={e.id}><span className="datebox">{new Date(e.event_date+'T12:00').getDate()}<small>{new Date(e.event_date+'T12:00').toLocaleDateString('es-GT',{month:'short'})}</small></span><div><strong>{e.title}</strong><small>{e.start_time?.slice(0,5)||'Todo el día'}</small></div></article>)}{!events.length&&<Empty text="No hay eventos próximos."/ >}</div></Page>}

function Budget({household,txs,refresh}:any){const [show,setShow]=useState(false);const expense=useMemo(()=>txs.filter((x:Tx)=>x.type==='expense').reduce((a:number,b:Tx)=>a+Number(b.amount),0),[txs]);const income=useMemo(()=>txs.filter((x:Tx)=>x.type==='income').reduce((a:number,b:Tx)=>a+Number(b.amount),0),[txs]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await supabase.from('transactions').insert({household_id:household.id,description:String(f.get('description')),amount:Number(f.get('amount')),type:String(f.get('type')),transaction_date:String(f.get('date'))});setShow(false);refresh()}return <Page title="Presupuesto" subtitle="Una vista sencilla de las finanzas compartidas."><div className="finance"><div><span>Ingresos</span><strong>{money(income)}</strong></div><div><span>Gastos</span><strong>{money(expense)}</strong></div><div><span>Balance</span><strong>{money(income-expense)}</strong></div></div><button className="primary compact" onClick={()=>setShow(!show)}><Plus size={17}/> Movimiento</button>{show&&<form className="panel formgrid" onSubmit={add}><input name="description" placeholder="Descripción" required/><input name="amount" type="number" step="0.01" min="0.01" placeholder="Monto" required/><select name="type"><option value="expense">Gasto</option><option value="income">Ingreso</option></select><input name="date" type="date" defaultValue={today()} required/><button>Guardar</button></form>}<div className="stack">{txs.map((t:Tx)=><article className="row" key={t.id}><span className={'moneydot '+t.type}>{t.type==='income'?'+':'−'}</span><div className="grow"><strong>{t.description}</strong><small>{new Date(t.transaction_date+'T12:00').toLocaleDateString('es-GT')}</small></div><b>{t.type==='income'?'+':'−'}{money(Number(t.amount))}</b></article>)}{!txs.length&&<Empty text="Aún no hay movimientos."/ >}</div></Page>}

function Family({household}:any){return <Page title="Mi familia" subtitle="Comparte este código para invitar a otra persona a tu hogar."><div className="invite"><span>CÓDIGO DE INVITACIÓN</span><strong>{household.invite_code}</strong><button onClick={()=>navigator.clipboard.writeText(household.invite_code)}>Copiar código</button></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/> Cerrar sesión</button></Page>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
